group: edge
language: java
jdk: oraclejdk8
install: true
before_install:
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk selfupdate
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - sdk use gradle
  - mkdir -p "$HOME/.sdkman/etc"
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
script:
  - gradle clean build
  - java -jar build/libs/*.jar &
  - sleep 10
  - curl -v --user user:pass localhost:8080 -H'content-type:application/json' -d'{"value":"test"}'
after_script:
  - gradle --stop
cache:
  directories:
    - $HOME/.gradle/
    - $HOME/.m2/
